const graph = {
  graph: [],
  links: [
    {source: 0, target: 1},
    {source: 0, target: 2},
    {source: 0, target: 3},
    {source: 0, target: 4},
    {source: 0, target: 5},
    {source: 0, target: 6},
    {source: 1, target: 3},
    {source: 1, target: 4},
    {source: 1, target: 5},
    {source: 1, target: 6},
    {source: 2, target: 4},
    {source: 2, target: 5},
    {source: 2, target: 6},
    {source: 3, target: 5},
    {source: 3, target: 6},
    {source: 5, target: 6},
    {source: 0, target: 7},
    {source: 1, target: 8},
    {source: 2, target: 9},
    {source: 3, target: 10},
    {source: 4, target: 11},
    {source: 5, target: 12},
    {source: 6, target: 13}],
  nodes: [
    {size: 60, id: 'Androsynth', type: 'circle'},
    {size: 10, id: 'Chenjesu', type: 'circle'},
    {size: 60, id: 'Ilwrath', type: 'circle'},
    {size: 10, id: 'Mycon', type: 'circle'},
    {size: 60, id: 'Spathi', type: 'circle'},
    {size: 10, id: 'Umgah', type: 'circle'},
    {size: 100, id: 'VUX', type: 'circle'},
    {size: 60, id: 'Guardian', type: 'circle'},
    {size: 10, id: 'Broodhmome', type: 'circle'},
    {size: 60, id: 'Avenger', type: 'circle'},
    {size: 10, id: 'Podship', type: 'circle'},
    {size: 60, id: 'Eluder', type: 'circle'},
    {size: 10, id: 'Drone', type: 'circle'},
    {size: 50, id: 'Intruder', type: 'circle'}],
}
export default graph
