/* eslint-disable quotes */

export const lyrics = [
  "Keeping time against the sun",
  "Save your words, I won't be gone for long",
  "Looking at me strange like some animal",
  "Just like the girl I used to love",
  "We get so carried away",
  "We get so enchanted by what we don't have",
  "We get so carried away",
  "We take our chances",
  "In the Garden of Eden",
  "I can read the writing on the wall",
  "Like I always do",
  "You're always crazed just like some animal",
  "Just like the love I used to know",
  "We get so carried away",
  "We get so enchanted by what we don't have",
  "We get so carried away",
  "We take our chances",
  "In the Garden of Eden",
  "Take your phone out in the rain",
  "Take your mask off or we will take it off for you",
  "We will, we will",
  "Taking orders in this place",
  "Think it over 'cause we feel like animals'",
  "When the snakes come marching in",
  "We get so carried away",
  "We get so enchanted by what we don't have",
  "We get so carried away",
  "We take our chances",
]
