/* eslint-disable quotes */

export const lyrics = [
  "Happy now, now we've parted",
  "Now you turned around from what we started",
  "Are you happy now?",
  "Did you just forget?",
  "Reconfiguring the landscape you now regret",
  "'Cause I'm sorry for all the mess we've made",
  "Couldn't see clear the way we both behaved",
  "Sometimes it feel just like a violent storm",
  "I couldn't recognize until it took hold",
  "Tearing right through me like a sweet look around",
  "It was too late before I knew its name",
  "Hope you're happy now, you've caught every threat",
  "Burning holes right through all the things we said",
  "'Cause I understand",
  "Happen to leave you right along",
  "But I'll remember it differently for what it was",
  "Happy now",
  "Happy now",
  "Happen to me",
  "Happy now",
  "Yes I understand",
  "Happen to leave you right along",
  "But I'll remember it differently for what it was",
]
