/* eslint-disable quotes */

export const lyrics = [
  "Walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
  "We'll be walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
  "We'll be feeling like there's no way away",
  "Oh no, don't think so",
  "Feeling like there's nothing lower",
  "Oh no, couldn't see",
  "Feels just like this is lost forever",
  "Oh no, don't think so",
  "Feel there's nothing left to discover",
  "Oh no, don't think so",
  "Walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
  "We'll be walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
  "We'll be feeling like there's no way away",
  "Oh no, don't think so",
  "Feeling like there's nothing lower",
  "Oh no, couldn't see",
  "Feels just like this is lost forever",
  "Oh no, don't think so",
  "Feel there's nothing left to discover",
  "Oh no, don't think so",
  "Looking in the mirror",
  "Dancing by youself",
  "Playing this song all night long",
  "With the snap of your fingers, I'll be there",
  "With the snap of your fingers, I'm right there",
  "Walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
  "We'll be walking underwater",
  "To float up and kiss me, girl",
  "When we're lying in your bed",
  "Dreaming castles in our heads",
]
