export const CREATE_OWN_BEACON = 'CREATE_OWN_BEACON'
export const CREATE_OWN_BEACON_ERROR = 'CREATE_OWN_BEACON_ERROR'

export const FOUND_BEACON = 'FOUND_BEACON'
export const REMOVE_BEACON = 'REMOVE_BEACON'

export const CONNECT_ERROR = 'CONNECT_ERROR'
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS'
export const CONNECT_CANCELED = 'CONNECT_CANCELED'

export const BEGIN_CONNECTING = 'BEGIN_CONNECTING'
