export const CREATE_BEACON = 'CREATE_BEACON'
export const CREATE_BEACON_ERROR = 'CREATE_BEACON_ERROR'

export const FIND_BEACON = 'FIND_BEACON'
export const REMOVE_BEACON = 'REMOVE_BEACON'

export const CONNECT_ERROR = 'CONNECT_ERROR'
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS'
export const CONNECT_CANCELED = 'CONNECT_CANCELED'

export const BEGIN_CONNECTING = 'BEGIN_CONNECTING'
